Repository aviferdman/Workshop-on-Software-Engineering-Project, pull requests merged in 2021-06, with the labels that each got.

#254 fixed publisher, fixed store search
  TradingSystem/AcceptanceTests/Tests/LiveNotification/AssignNotificationAT.cs
  TradingSystem/AcceptanceTests/Tests/LiveNotification/PurchaseNotificationAT.cs
  TradingSystem/AcceptanceTests/Tests/LiveNotification/RemoveMangerNotificationAT.cs
  TradingSystem/AcceptanceTests/Tests/LiveNotification/RemoveOwnerNotificationAT.cs
  TradingSystem/TradingSystem.WebApi/Notifications/LoggedInController.cs
  TradingSystem/TradingSystem/Business/Market/MarketStores.cs
  TradingSystem/TradingSystem/Business/Market/MarketUsers.cs
  TradingSystem/TradingSystem/DAL/MarketContext.cs
  TradingSystem/TradingSystem/DAL/ProxyMarketContext.cs
  TradingSystem/TradingSystem/PublisherComponent/PublisherManagement.cs
Labels: bug

#266 Initializing file
  TradingSystem/TradingSystem/Service/SetupService.cs
  TradingSystem/TradingSystem/Service/init.txt
Labels: features

#269 added statis
  TradingSystem/TradingSystem/Business/Market/MarketUsers.cs
  TradingSystem/TradingSystem/Business/Market/Statistics.cs
  TradingSystem/TradingSystem/DAL/MarketContext.cs
  TradingSystem/TradingSystem/DAL/ProxyMarketContext.cs
  TradingSystem/TradingSystem/DAL/UsersDAL.cs
  TradingSystem/TradingSystemTests/DBTests/PurchaseTests.cs
Labels: features

#280 pretty toffee
  TradingSystem/AcceptanceTests/Init_Test.cs
  TradingSystem/TradingSystem/Service/SetupService.cs
  TradingSystem/TradingSystem/init.txt
Labels: bug, features

#299 added locks in db access
  TradingSystem/TradingSystem.WebApi/LoggerMessages.txt
  TradingSystem/TradingSystem.WebApi/marketDBTests.db
  TradingSystem/TradingSystem.WebApi/marketDBTests.db-shm
  TradingSystem/TradingSystem.WebApi/marketDBTests.db-wal
  TradingSystem/TradingSystem/Business/Market/BidsPackage/BidsManager.cs
  TradingSystem/TradingSystem/Business/Market/MarketUsers.cs
  TradingSystem/TradingSystem/Business/Market/UserPackage/ShoppingCart.cs
  TradingSystem/TradingSystem/DAL/MarketContext.cs
  TradingSystem/TradingSystem/DAL/ProxyMarketContext.cs
Labels: bug

#301 fixes in discount
  TradingSystem/TradingSystem.WebApi/LoggerMessages.txt
  TradingSystem/TradingSystem.WebApi/marketDBTests.db
  TradingSystem/TradingSystem/Business/Market/MarketRules.cs
  TradingSystem/TradingSystem/Business/Market/StorePackage/Predicates/MarketRuleRequest.cs
  TradingSystem/TradingSystem/Business/Market/StorePackage/Predicates/MarketRulesRequestType1.cs
  TradingSystem/TradingSystem/Business/Market/StorePackage/Predicates/MarketRulesRequestType2.cs
  TradingSystem/TradingSystem/Business/Market/StorePackage/Predicates/MarketRulesRequestType3.cs
  TradingSystem/TradingSystem/Business/Market/StorePackage/Predicates/MarketRulesRequestType4.cs
  TradingSystem/TradingSystem/Business/Market/StorePackage/Predicates/MarketRulesRequestType5.cs
  TradingSystem/TradingSystem/Business/Market/StorePackage/Predicates/MarketRulesRequestType6.cs
  TradingSystem/TradingSystem/Business/Market/StorePackage/Predicates/MarketRulesRequestType7.cs
  TradingSystem/TradingSystem/Business/Market/StorePackage/Predicates/MarketRulesRequestType8.cs
  TradingSystem/TradingSystem/DAL/MarketContext.cs
  TradingSystem/TradingSystem/Service/MarketRulesService.cs
  TradingSystem/TradingSystemTests/DBTests/MarketRulesTests.cs
  TradingSystem/TradingSystemTests/IntegrationTests/MarketRulesTests.cs
Labels: bug

#307 Boaz client bids
  TradingSystem/AcceptanceTests/AppInterface/Data/ProductInfo.cs
  TradingSystem/TradingSystem.WebApi/Controllers/HistoryController.cs
  TradingSystem/TradingSystem.WebApi/Controllers/StoreBidsController.cs
  TradingSystem/TradingSystem.WebApi/Controllers/StorePermissionsController.cs
  TradingSystem/TradingSystem.WebApi/Controllers/StoresController.cs
  TradingSystem/TradingSystem.WebApi/DTO/Products/ProductSearchDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Bids/BidPolicyChangeDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Bids/BidStatus_Api.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Bids/BidStoreDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Bids/BidUserDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Bids/CreateBidOfferDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Bids/CustomerBidParamsDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Bids/CustomerNegotiateBidParamsDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Bids/OwnerBidParamsDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Bids/OwnerNegotiateParamsDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/StoreInfoActionDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/StoreInfoDTO.cs
  TradingSystem/TradingSystem.WebClient/src/App.css
  TradingSystem/TradingSystem.WebClient/src/api.js
  TradingSystem/TradingSystem.WebClient/src/components/HomeProduct.js
  TradingSystem/TradingSystem.WebClient/src/components/HomeProducts.js
  TradingSystem/TradingSystem.WebClient/src/components/SimpleModal.css
  TradingSystem/TradingSystem.WebClient/src/components/SimpleModal.js
  TradingSystem/TradingSystem.WebClient/src/formsUtil/formFieldInfo.js
  TradingSystem/TradingSystem.WebClient/src/pages/ShoppingCart/ShoppingCart.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/Discounts.css
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Store.css
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Store.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/AddBid.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/BidEditContent.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/BidRecordStore.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/BidRecordsStore.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/storeBids.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreCreateForm.js
  TradingSystem/TradingSystem.WebClient/src/pages/UserBids/BidRecord.js
  TradingSystem/TradingSystem.WebClient/src/pages/UserBids/BidRecordUser.js
  TradingSystem/TradingSystem.WebClient/src/pages/UserBids/BidRecordsUser.js
  TradingSystem/TradingSystem.WebClient/src/pages/UserBids/userBids.js
  TradingSystem/TradingSystem.WebClient/src/routes.js
Labels: features

#308 Boaz client statistics
  TradingSystem/TradingSystem.WebApi/Controllers/StatisticsController.cs
  TradingSystem/TradingSystem.WebApi/DTO/StatisticsDTO.cs
  TradingSystem/TradingSystem.WebApi/Notifications/LoggedInController.cs
  TradingSystem/TradingSystem.WebApi/Notifications/Notification.cs
  TradingSystem/TradingSystem.WebApi/Notifications/NotificationKind.cs
  TradingSystem/TradingSystem.WebApi/Notifications/Subscriber.cs
  TradingSystem/TradingSystem.WebApi/Notifications/SubscriberStatistics.cs
  TradingSystem/TradingSystem.WebApi/Notifications/WebApiSubsriberBase.cs
  TradingSystem/TradingSystem.WebApi/Utils.cs
  TradingSystem/TradingSystem.WebClient/src/App.js
  TradingSystem/TradingSystem.WebClient/src/api.js
  TradingSystem/TradingSystem.WebClient/src/components/Navbar/SidebarData.js
  TradingSystem/TradingSystem.WebClient/src/formsUtil/DateFormField.js
  TradingSystem/TradingSystem.WebClient/src/pages/Admin/Statistics.js
  TradingSystem/TradingSystem.WebClient/src/utils.js
Labels: features

#309 Web API - missing return values validation fixes
  TradingSystem/TradingSystem.WebApi/Controllers/HistoryController.cs
  TradingSystem/TradingSystem.WebApi/Controllers/StoreBidsController.cs
Labels: bug

#311 Client rules edit
  TradingSystem/TradingSystem.WebApi/Controllers/StoreRulesController.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Discounts/DiscountParamsSimpleCreationDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Discounts/DiscountParamsSimpleDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Discounts/DiscountParamsSimpleEditDTO.cs
  TradingSystem/TradingSystem.WebApi/DTO/Store/Discounts/DiscountRefActionDTO.cs
  TradingSystem/TradingSystem.WebApi/LoggerMessages.txt
  TradingSystem/TradingSystem.WebApi/marketDBTests.db
  TradingSystem/TradingSystem.WebClient/src/api.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/AddSimpleDiscount.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/Discounts.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/EditSimpleDiscount.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/SimpleDiscount.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/Policy.js
  TradingSystem/TradingSystem.WebClient/src/utils.js
Labels: features

#312 Boaz fixes
  TradingSystem/TradingSystem.WebApi/Controllers/ProductsController.cs
  TradingSystem/TradingSystem.WebClient/src/App.js
  TradingSystem/TradingSystem.WebClient/src/api.js
  TradingSystem/TradingSystem.WebClient/src/components/CartProduct.js
  TradingSystem/TradingSystem.WebClient/src/components/Filter.js
  TradingSystem/TradingSystem.WebClient/src/components/HomeProduct.js
  TradingSystem/TradingSystem.WebClient/src/header.js
  TradingSystem/TradingSystem.WebClient/src/pages/ShoppingCart/ShoppingCart.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/AddComplexDiscount.css
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/AddSimpleDiscount.css
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/AddSimpleDiscount.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/EditSimpleDiscount.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/AddPolicy.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/Policy.css
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/Policy.js
  TradingSystem/TradingSystem.WebClient/src/pages/mainPage/Home.js
  TradingSystem/TradingSystem.WebClient/src/utils.js
  TradingSystem/TradingSystem/Business/Clients/ExternalSystemClient.cs
Labels: bug, features

#313 Client - discount and policy displays
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/SimpleDiscount.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/PolicyRecord.js
Labels: bug

#315 Client bids policy change
  TradingSystem/TradingSystem.WebApi/App.config
  TradingSystem/TradingSystem.WebApi/Controllers/StoreBidsController.cs
  TradingSystem/TradingSystem.WebApi/LoggerMessages.txt
  TradingSystem/TradingSystem.WebApi/Startup.cs
  TradingSystem/TradingSystem.WebApi/marketDBTests.db
  TradingSystem/TradingSystem.WebClient/src/api.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/storeBids.css
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/storeBids.js
  TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreCreateForm.js
Labels: features
